my_string = input('Введите фразу или выражение: ')
print('Количество символов введённого текста: ', len(my_string))
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(' ', ''))
print('Первый символ строки: ', my_string[0])
print('Последний символ строки: ', my_string[-1])
